# Generated by Django 5.1.1 on 2025-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='A0AJelgmAFP9dvOhvZwaeCaek3lua8x2', editable=False, max_length=32, unique=True),
        ),
    ]
